name: Core Feature Alert

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - src/lib/features/client-feature-toggles/*
      - src/lib/features/frontend-api/*

jobs:
  notify-core-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch PR Creator's Username
        id: pr-creator
        run: echo "PR_CREATOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV

      - name: Post a notification about core feature changes
        uses: actions/github-script@v6
        with:
          script: |
            const prCreator = process.env.PR_CREATOR;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `@${prCreator}, core features have been modified in this pull request. Please review!`
            })
      # - name: Add reviewers to the PR
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const reviewers = ['FredrikOseberg'];
      #       github.rest.pulls.requestReviewers({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: context.payload.pull_request.number,
      #         reviewers: reviewers,
      #       });